const products = [
    {
        "_id": 1,
        "name": "modern storage bedroom for couples",
        "price": 175000,
        "prix": 200000,
        "quantity": 1,
        "bigImage": ["http://localhost:3000/home5.jpg",
                    "http://localhost:3000/home5.jpg",
                    "http://localhost:3000/home5.jpg",
                    "http://localhost:3000/home5.jpg"
                ],
        "smallImage": ["http://localhost:3000/home5.jpg",
                    "http://localhost:3000/home5.jpg",
                    "http://localhost:3000/home5.jpg",
                    "http://localhost:3000/home5.jpg"
                ],
        "alt": "alt1",
        "description": "0Lorem ipsum dolor sit amet consectetur adipisicing elit. Facere natus cum ex rerum possimus libero ipsum soluta a aspernatur delectus qui eos, tempore sapiente incidunt sint ea maiores repellendus esse!",
        "colors": ["pink", "white", "custom"],
        "infos": ["Places", "Height", "Width", "Material"],
        "infosvalue": ["4", "500cm", "50cm", "Chene"],
        "reviewn1": "Sarah",
        "reviewn2": "Faizal",
        "reviewd1": "7/3/24",
        "reviewd2": "1/3/24",
        "reviewt1": "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Beatae hic impedit ipsum aperiam, ipsam expedita fuga quidem sint dolorum inventore.",
        "reviewt2": "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Beatae hic impedit ipsum aperiam, ipsam expedita fuga quidem sint dolorum inventora."
    },
    {
        "_id": 2,
        "name": "dimmable ceiling light modern",
        "price": 43000,
        "prix": 51000,
        "quantity": 1,
        "bigImage": ["http://localhost:3000/home2.jpg",
                    "http://localhost:3000/home2.jpg",
                    "http://localhost:3000/home2.jpg",
                    "http://localhost:3000/home2.jpg"
                ],
        "smallImage": ["http://localhost:3000/home2.jpg",
                    "http://localhost:3000/home2.jpg",
                    "http://localhost:3000/home2.jpg",
                    "http://localhost:3000/home2.jpg"
                ],
        "alt": "alt2",
        "description": "1Lorem ipsum dolor sit amet consectetur adipisicing elit. Facere natus cum ex rerum possimus libero ipsum soluta a aspernatur delectus qui eos, tempore sapiente incidunt sint ea maiores repellendus esse!",
        "colors": ["red", "dark blue", "black"],
        "infos": ["Brand", "Activity", "Material", "Gender"],
        "infosvalue": ["Kappa", "Running", "Fleece", "women"],
        "reviewn1": "Sarah",
        "reviewn2": "Faizal",
        "reviewd1": "7/3/24",
        "reviewd2": "1/3/24",
        "reviewt1": "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Beatae hic impedit ipsum aperiam, ipsam expedita fuga quidem sint dolorum inventore.",
        "reviewt2": "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Beatae hic impedit ipsum aperiam, ipsam expedita fuga quidem sint dolorum inventora."
    },
    {
        "_id": 3,
        "name": "vonanda velvet sofa couch",
        "price": 65000,
        "prix": 77000,
        "quantity": 1,
        "bigImage": ["http://localhost:3000/home1.jpg",
                    "http://localhost:3000/home1.jpg",
                    "http://localhost:3000/home1.jpg",
                    "http://localhost:3000/home1.jpg"
                ],
        "smallImage": ["http://localhost:3000/home1.jpg",
                    "http://localhost:3000/home1.jpg",
                    "http://localhost:3000/home1.jpg",
                    "http://localhost:3000/home1.jpg"
                ],
        "alt": "alt3",
        "description": "2Lorem ipsum dolor sit amet consectetur adipisicing elit. Facere natus cum ex rerum possimus libero ipsum soluta a aspernatur delectus qui eos, tempore sapiente incidunt sint ea maiores repellendus esse!",
        "colors": ["grey", "blue", "white"],
        "infos": ["Brand", "Activity", "Material", "Gender"],
        "infosvalue": ["Kappa", "Running", "Fleece", "women"],
        "reviewn1": "Sarah",
        "reviewn2": "Faizal",
        "reviewd1": "7/3/24",
        "reviewd2": "1/3/24",
        "reviewt1": "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Beatae hic impedit ipsum aperiam, ipsam expedita fuga quidem sint dolorum inventore.",
        "reviewt2": "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Beatae hic impedit ipsum aperiam, ipsam expedita fuga quidem sint dolorum inventora."
    },
    {
        "_id": 4,
        "name": "modern storage cabinet",
        "price": 300000,
        "prix": 370000,
        "quantity": 1,
        "bigImage": ["http://localhost:3000/home3.jpg",
                    "http://localhost:3000/home3.jpg",
                    "http://localhost:3000/home3.jpg",
                    "http://localhost:3000/home3.jpg"
                ],
        "smallImage": ["http://localhost:3000/home3.jpg",
                    "http://localhost:3000/home3.jpg",
                    "http://localhost:3000/home3.jpg",
                    "http://localhost:3000/home3.jpg"
                ],
        "alt": "alt4",
        "description": "3Lorem ipsum dolor sit amet consectetur adipisicing elit. Facere natus cum ex rerum possimus libero ipsum soluta a aspernatur delectus qui eos, tempore sapiente incidunt sint ea maiores repellendus esse!",
        "colors": ["white", "maroon", "black"],
        "infos": ["Brand", "Activity", "Material", "Gender"],
        "infosvalue": ["Kappa", "Running", "Fleece", "women"],
        "reviewn1": "Sarah",
        "reviewn2": "Faizal",
        "reviewd1": "7/3/24",
        "reviewd2": "1/3/24",
        "reviewt1": "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Beatae hic impedit ipsum aperiam, ipsam expedita fuga quidem sint dolorum inventore.",
        "reviewt2": "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Beatae hic impedit ipsum aperiam, ipsam expedita fuga quidem sint dolorum inventora."
    },    
    {
        "_id": 5,
        "name": "vonanda velvet chair",
        "price": 22000,
        "prix": 26000,
        "quantity": 1,
        "bigImage": ["http://localhost:3000/home4.jpg",
                    "http://localhost:3000/home4.jpg",
                    "http://localhost:3000/home4.jpg",
                    "http://localhost:3000/home4.jpg"
                ],
        "smallImage": ["http://localhost:3000/home4.jpg",
                    "http://localhost:3000/home4.jpg",
                    "http://localhost:3000/home4.jpg",
                    "http://localhost:3000/home4.jpg"
                ],
        "alt": "alt5",
        "description": "4Lorem ipsum dolor sit amet consectetur adipisicing elit. Facere natus cum ex rerum possimus libero ipsum soluta a aspernatur delectus qui eos, tempore sapiente incidunt sint ea maiores repellendus esse!",
        "colors": ["green", "white", "black", "red", "blue", "yellow", "orange"],
        "infos": ["Brand", "Display", "Resolution", ""],
        "infosvalue": ["Samsung", "52'", "800x1200px", ""],
        "reviewn1": "Sarah",
        "reviewn2": "Faizal",
        "reviewd1": "7/3/24",
        "reviewd2": "1/3/24",
        "reviewt1": "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Beatae hic impedit ipsum aperiam, ipsam expedita fuga quidem sint dolorum inventore.",
        "reviewt2": "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Beatae hic impedit ipsum aperiam, ipsam expedita fuga quidem sint dolorum inventora."
    },
    {
        "_id": 6,
        "name": "Men Slip On Shoes Casual with Arch Support Insoles",
        "price": 19000,
        "prix": 23000,
        "quantity": 1,
        "bigImage": ["http://localhost:3000/shoe1-1.jpg",
                    "http://localhost:3000/shoe1-1.jpg",
                    "http://localhost:3000/shoe1-1.jpg",
                    "http://localhost:3000/shoe1-1.jpg"
                ],
        "smallImage": ["http://localhost:3000/shoe1-1.jpg",
                    "http://localhost:3000/shoe1-1.jpg",
                    "http://localhost:3000/shoe1-1.jpg",
                    "http://localhost:3000/shoe1-1.jpg"
                ],
        "alt": "alt6",
        "description": "5Lorem ipsum dolor sit amet consectetur adipisicing elit. Facere natus cum ex rerum possimus libero ipsum soluta a aspernatur delectus qui eos, tempore sapiente incidunt sint ea maiores repellendus esse!",
        "colors": ["green", "white", "black", "red", "blue", "yellow", "orange"],
        "infos": ["Brand", "Activity", "Material", "Model name"],
        "infosvalue": ["Kappa", "Running", "Fleece", "Superres"],
        "reviewn1": "Sarah",
        "reviewn2": "Faizal",
        "reviewd1": "7/3/24",
        "reviewd2": "1/3/24",
        "reviewt1": "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Beatae hic impedit ipsum aperiam, ipsam expedita fuga quidem sint dolorum inventore.",
        "reviewt2": "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Beatae hic impedit ipsum aperiam, ipsam expedita fuga quidem sint dolorum inventora."
    },
    {
        "_id": 7,
        "name": "air force one",
        "price": 22500,
        "prix": 27000,
        "quantity": 1,
        "bigImage": ["http://localhost:3000/shoe5.jpg",
                    "http://localhost:3000/shoe5.jpg",
                    "http://localhost:3000/shoe5.jpg",
                    "http://localhost:3000/shoe5.jpg"
                ],
        "smallImage": ["http://localhost:3000/shoe5.jpg",
                    "http://localhost:3000/shoe5.jpg",
                    "http://localhost:3000/shoe5.jpg",
                    "http://localhost:3000/shoe5.jpg"
                ],
        "alt": "alt7",
        "description": "6Lorem ipsum dolor sit amet consectetur adipisicing elit. Facere natus cum ex rerum possimus libero ipsum soluta a aspernatur delectus qui eos, tempore sapiente incidunt sint ea maiores repellendus esse!",
        "colors": ["blue", "black", "custom"],
        "infos": ["Brand", "Edition", "Material", "Gender"],
        "infosvalue": ["Nike", "2k21", "Fleece", "All"],
        "reviewn1": "Sarah",
        "reviewn2": "Faizal",
        "reviewd1": "7/3/24",
        "reviewd2": "1/3/24",
        "reviewt1": "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Beatae hic impedit ipsum aperiam, ipsam expedita fuga quidem sint dolorum inventore.",
        "reviewt2": "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Beatae hic impedit ipsum aperiam, ipsam expedita fuga quidem sint dolorum inventora."
    },
    {
        "_id": 8,
        "name": "new air force",
        "price": 25000,
        "prix": 29000,
        "quantity": 1,
        "bigImage": ["http://localhost:3000/shoe3.jpg",
                    "http://localhost:3000/shoe3.jpg",
                    "http://localhost:3000/shoe3.jpg",
                    "http://localhost:3000/shoe3.jpg"
                ],
        "smallImage": ["http://localhost:3000/shoe3.jpg",
                    "http://localhost:3000/shoe3.jpg",
                    "http://localhost:3000/shoe3.jpg",
                    "http://localhost:3000/shoe3.jpg"
                ],
        "alt": "alt8", 
        "description": "7Lorem ipsum dolor sit amet consectetur adipisicing elit. Facere natus cum ex rerum possimus libero ipsum soluta a aspernatur delectus qui eos, tempore sapiente incidunt sint ea maiores repellendus esse!",
        "colors": ["white", "pink", "custom"],
        "infos": ["Brand", "Edition", "Material", "Gender"],
        "infosvalue": ["Nike", "2k23", "Fleece", "Girl"],
        "reviewn1": "Sarah",
        "reviewn2": "Faizal",
        "reviewd1": "7/3/24",
        "reviewd2": "1/3/24",
        "reviewt1": "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Beatae hic impedit ipsum aperiam, ipsam expedita fuga quidem sint dolorum inventore.",
        "reviewt2": "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Beatae hic impedit ipsum aperiam, ipsam expedita fuga quidem sint dolorum inventora."
    },
    {
        "_id": 9,
        "name": "women college shoe",
        "price": 22000,
        "prix": 26500,
        "quantity": 1,
        "bigImage": ["http://localhost:3000/shoe2.jpg",
                    "http://localhost:3000/shoe2.jpg",
                    "http://localhost:3000/shoe2.jpg",
                    "http://localhost:3000/shoe2.jpg"
                ],
        "smallImage": ["http://localhost:3000/shoe2.jpg",
                    "http://localhost:3000/shoe2.jpg",
                    "http://localhost:3000/shoe2.jpg",
                    "http://localhost:3000/shoe2.jpg"
                ],
        "alt": "alt9",
        "description": "8Lorem ipsum dolor sit amet consectetur adipisicing elit. Facere natus cum ex rerum possimus libero ipsum soluta a aspernatur delectus qui eos, tempore sapiente incidunt sint ea maiores repellendus esse!",
        "colors": ["pink", "yellow", "white"],
        "infos": ["Brand", "Activity", "Material", "Gender"],
        "infosvalue": ["Kappa", "Running", "Fleece", "Women"],
        "reviewn1": "Sarah",
        "reviewn2": "Faizal",
        "reviewd1": "7/3/24",
        "reviewd2": "1/3/24",
        "reviewt1": "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Beatae hic impedit ipsum aperiam, ipsam expedita fuga quidem sint dolorum inventore.",
        "reviewt2": "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Beatae hic impedit ipsum aperiam, ipsam expedita fuga quidem sint dolorum inventora."
    },
    {
        "_id": 10,
        "name": "women summer tosca shoe",
        "price": 18000,
        "prix": 20500,
        "quantity": 1,
        "bigImage": ["http://localhost:3000/shoe4.jpg", 
                    "http://localhost:3000/shoe4.jpg",
                    "http://localhost:3000/shoe4.jpg", 
                    "http://localhost:3000/shoe4.jpg"
                ],
        "smallImage": ["http://localhost:3000/shoe4.jpg", 
                    "http://localhost:3000/shoe4.jpg",
                    "http://localhost:3000/shoe4.jpg", 
                    "http://localhost:3000/shoe4.jpg"
                ],
        "alt": "alt10",
        "description": "9Lorem ipsum dolor sit amet consectetur adipisicing elit. Facere natus cum ex rerum possimus libero ipsum soluta a aspernatur delectus qui eos, tempore sapiente incidunt sint ea maiores repellendus esse!",
        "colors": ["green", 
                    "maroon", 
                    "black"
                ],
        "infos": ["Brand", "Activity", "Material", "Gender"],
        "infosvalue": ["Kappa", "Running", "Fleece", "Women"],
        "reviewn1": "Sarah",
        "reviewn2": "Faizal",
        "reviewd1": "7/3/24",
        "reviewd2": "1/3/24",
        "reviewt1": "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Beatae hic impedit ipsum aperiam, ipsam expedita fuga quidem sint dolorum inventore.",
        "reviewt2": "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Beatae hic impedit ipsum aperiam, ipsam expedita fuga quidem sint dolorum inventora."
    },
    {
        "_id": 11,
        "name": "pc lenovo thinkpad",
        "price": 130000,
        "prix": 150000,
        "quantity": 1,
        "bigImage": ["http://localhost:3000/electronic1.jpg",
                    "http://localhost:3000/electronic1.jpg",
                    "http://localhost:3000/electronic1.jpg",
                    "http://localhost:3000/electronic1.jpg"
                ],
        "smallImage": ["http://localhost:3000/electronic1.jpg",
                    "http://localhost:3000/electronic1.jpg",
                    "http://localhost:3000/electronic1.jpg",
                    "http://localhost:3000/electronic1.jpg"
                ],
        "alt": "alt11",
        "description": "10Lorem ipsum dolor sit amet consectetur adipisicing elit. Facere natus cum ex rerum possimus libero ipsum soluta a aspernatur delectus qui eos, tempore sapiente incidunt sint ea maiores repellendus esse!",
        "colors": ["white", "black", "dark-blue"],
        "infos": ["Processeur", "RAM", "ROM", "Display"],
        "infosvalue": ["Intel Core i5-7200 CPU 2.50GHz 2.70GHz", "8.00GB", "1To", "22'"],
        "reviewn1": "Sarah",
        "reviewn2": "Faizal",
        "reviewd1": "7/3/24",
        "reviewd2": "1/3/24",
        "reviewt1": "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Beatae hic impedit ipsum aperiam, ipsam expedita fuga quidem sint dolorum inventore.",
        "reviewt2": "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Beatae hic impedit ipsum aperiam, ipsam expedita fuga quidem sint dolorum inventora."
    },
    {
        "_id": 12,
        "name": "casque lenovo",
        "price": 8000,
        "prix": 9000,
        "quantity": 1,
        "bigImage": ["http://localhost:3000/electronic3.jpg",
                    "http://localhost:3000/electronic3.jpg",
                    "http://localhost:3000/electronic3.jpg",
                    "http://localhost:3000/electronic3.jpg"
                ],
        "smallImage": ["http://localhost:3000/electronic3.jpg",
                    "http://localhost:3000/electronic3.jpg",
                    "http://localhost:3000/electronic3.jpg",
                    "http://localhost:3000/electronic3.jpg"
                ],
        "alt": "alt12",
        "description": "11Lorem ipsum dolor sit amet consectetur adipisicing elit. Facere natus cum ex rerum possimus libero ipsum soluta a aspernatur delectus qui eos, tempore sapiente incidunt sint ea maiores repellendus esse!",
        "colors": ["grey",
                    "black",
                    "red"
                ],
        "infos": ["Signal", "Consumption", "CarrierLock", "Brand"],
        "infosvalue": ["Stable signal", "Low power consumption", "High endurance", "Lenovo"],
        "reviewn1": "Sarah",
        "reviewn2": "Faizal",
        "reviewd1": "7/3/24",
        "reviewd2": "1/3/24",
        "reviewt1": "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Beatae hic impedit ipsum aperiam, ipsam expedita fuga quidem sint dolorum inventore.",
        "reviewt2": "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Beatae hic impedit ipsum aperiam, ipsam expedita fuga quidem sint dolorum inventora."
    },  
    {
        "_id": 13,
        "name": "silicon case apple iphone 11",
        "price": 15000,
        "prix": 17500,
        "quantity": 1,
        "bigImage": ["http://localhost:3000/iphone11-silicone-case.png", 
                    "http://localhost:3000/iphone11-silicone-case.png",
                    "http://localhost:3000/iphone11-silicone-case.png",
                    "http://localhost:3000/iphone11-silicone-case.png"
                ],
        "smallImage": ["http://localhost:3000/iphone11-silicone-case.png", 
                    "http://localhost:3000/iphone11-silicone-case.png",
                    "http://localhost:3000/iphone11-silicone-case.png",
                    "http://localhost:3000/iphone11-silicone-case.png"
                ],
        "alt": "alt13",
        "description": "12Lorem ipsum dolor sit amet consectetur adipisicing elit. Facere natus cum ex rerum possimus libero ipsum soluta a aspernatur delectus qui eos, tempore sapiente incidunt sint ea maiores repellendus esse!",
        "colors": ["pink",
                    "red",
                    "black",
                    "blue",
                    "white",
                    "green",
                    "yellow",
                    "purple"
                ],
        "infos": ["Material"],
        "infosvalue": ["Silicone souple"],
        "reviewn1": "Sarah",
        "reviewn2": "Faizal",
        "reviewd1": "7/3/24",
        "reviewd2": "1/3/24",
        "reviewt1": "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Beatae hic impedit ipsum aperiam, ipsam expedita fuga quidem sint dolorum inventore.",
        "reviewt2": "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Beatae hic impedit ipsum aperiam, ipsam expedita fuga quidem sint dolorum inventora."
    },
    {
        "_id": 14,
        "name": "apple iphone 11",
        "price": 115000,
        "prix": 138000,
        "quantity": 1,
        "bigImage": ["http://localhost:3000/iphone11.png", 
                    "http://localhost:3000/iphone11.png",
                    "http://localhost:3000/iphone11.png",
                    "http://localhost:3000/iphone11.png"
                ],
        "smallImage": ["http://localhost:3000/iphone11.png", 
                    "http://localhost:3000/iphone11.png",
                    "http://localhost:3000/iphone11.png",
                    "http://localhost:3000/iphone11.png"
                ],
        "alt": "alt14",
        "description": "13Lorem ipsum dolor sit amet consectetur adipisicing elit. Facere natus cum ex rerum possimus libero ipsum soluta a aspernatur delectus qui eos, tempore sapiente incidunt sint ea maiores repellendus esse!",
        "colors": ["yellow",
                    "red",
                    "black",
                    "white",
                    "green",
                    "mediumpurple",
                ],
        "infos": ["Capacity", "Display", "RAM", "CarrierLock", "Battery"],
        "infosvalue": ["64GB", "6.1'", "4Go", "SIM Locked", "3110 mAh"],
        "reviewn1": "Sarah",
        "reviewn2": "Faizal",
        "reviewd1": "7/3/24",
        "reviewd2": "1/3/24",
        "reviewt1": "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Beatae hic impedit ipsum aperiam, ipsam expedita fuga quidem sint dolorum inventore.",
        "reviewt2": "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Beatae hic impedit ipsum aperiam, ipsam expedita fuga quidem sint dolorum inventora."
    },
    {
        "_id": 15,
        "name": "apple iphone 13",
        "price": 215000,
        "prix": 248000,
        "quantity": 1,
        "bigImage": ["http://localhost:3000/iphone13.jpg", 
                    "http://localhost:3000/iphone13.jpg",
                    "http://localhost:3000/iphone13.jpg",
                    "http://localhost:3000/iphone13.jpg"
                ],
        "smallImage": ["http://localhost:3000/iphone13.jpg", 
                    "http://localhost:3000/iphone13.jpg",
                    "http://localhost:3000/iphone13.jpg",
                    "http://localhost:3000/iphone13.jpg"
                ],
        "alt": "alt15",
        "description": "14Lorem ipsum dolor sit amet consectetur adipisicing elit. Facere natus cum ex rerum possimus libero ipsum soluta a aspernatur delectus qui eos, tempore sapiente incidunt sint ea maiores repellendus esse!",
        "colors": ["pink",
                    "red",
                    "darkblue",
                    "whitesmoke"
                ],
        "infos": ["Capacity", "Display", "RAM", "Battery"],
        "infosvalue": ["512GB", "6.1'", "4Go", "100%"],
        "reviewn1": "Sarah",
        "reviewn2": "Faizal",
        "reviewd1": "7/3/24",
        "reviewd2": "1/3/24",
        "reviewt1": "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Beatae hic impedit ipsum aperiam, ipsam expedita fuga quidem sint dolorum inventore.",
        "reviewt2": "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Beatae hic impedit ipsum aperiam, ipsam expedita fuga quidem sint dolorum inventora."
    },
    {
        "_id": 16,
        "name": "apple iphone 14 promax",
        "price": 420000,
        "prix": 499000,
        "quantity": 1,
        "bigImage": ["http://localhost:3000/iphone14ProMax.jpg", 
                    "http://localhost:3000/iphone14ProMax.jpg",
                    "http://localhost:3000/iphone14ProMax.jpg",
                    "http://localhost:3000/iphone14ProMax.jpg"
                ],
        "smallImage": ["http://localhost:3000/iphone14ProMax.jpg", 
                    "http://localhost:3000/iphone14ProMax.jpg",
                    "http://localhost:3000/iphone14ProMax.jpg",
                    "http://localhost:3000/iphone14ProMax.jpg"
                ],
        "alt": "alt16",
        "description": "15Lorem ipsum dolor sit amet consectetur adipisicing elit. Facere natus cum ex rerum possimus libero ipsum soluta a aspernatur delectus qui eos, tempore sapiente incidunt sint ea maiores repellendus esse!",
        "colors": ["midnightblue",
                    "black",
                    "#eec78c",
                    "whitesmoke"
                ],
        "info" : [alt="alt16",alt1="alt17"],
        "infos": ["Capacity", "Material", "RAM", "Battery", "Port", "Display"],
        "infosvalue": ["1To", "Titanium", "8 Go", "100%", "USB-C", "6.7'"],
        "reviewn1": "Sarah",
        "reviewn2": "Faizal",
        "reviewd1": "7/3/24",
        "reviewd2": "1/3/24",
        "reviewt1": "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Beatae hic impedit ipsum aperiam, ipsam expedita fuga quidem sint dolorum inventore.",
        "reviewt2": "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Beatae hic impedit ipsum aperiam, ipsam expedita fuga quidem sint dolorum inventora."
    },
    {
        "_id": 17,
        "name": "google pixel 7 pro",
        "price": 160000,
        "prix": 182000,
        "quantity": 1,
        "bigImage": ["http://localhost:3000/googlePixel.jpg", 
                    "http://localhost:3000/googlePixel.jpg",
                    "http://localhost:3000/googlePixel.jpg",
                    "http://localhost:3000/googlePixel.jpg"
                ],
        "smallImage": ["http://localhost:3000/googlePixel.jpg", 
                    "http://localhost:3000/googlePixel.jpg",
                    "http://localhost:3000/googlePixel.jpg",
                    "http://localhost:3000/googlePixel.jpg"
                ],
        "alt": "alt17",
        "description": "16Lorem ipsum dolor sit amet consectetur adipisicing elit. Facere natus cum ex rerum possimus libero ipsum soluta a aspernatur delectus qui eos, tempore sapiente incidunt sint ea maiores repellendus esse!",
        "colors": [ "snow",
                    "tan",
                    "black",
                ],
        "infos": ["Battery", "Display", "Capacity", "Port"],
        "infosvalue": ["5000 mAh", "6.7'", "256GB", "USB-C 3.1"],
        "reviewn1": "Sarah",
        "reviewn2": "Faizal",
        "reviewd1": "7/3/24",
        "reviewd2": "1/3/24",
        "reviewt1": "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Beatae hic impedit ipsum aperiam, ipsam expedita fuga quidem sint dolorum inventore.",
        "reviewt2": "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Beatae hic impedit ipsum aperiam, ipsam expedita fuga quidem sint dolorum inventora."
    },
    {
        "_id": 18,
        "name": "one plus 12",
        "price": 191000,
        "prix": 213000,
        "quantity": 1,
        "bigImage": ["http://localhost:3000/onePlus.jpg", 
                    "http://localhost:3000/onePlus.jpg",
                    "http://localhost:3000/onePlus.jpg",
                    "http://localhost:3000/onePlus.jpg"
                ],
        "smallImage": ["http://localhost:3000/onePlus.jpg", 
                    "http://localhost:3000/onePlus.jpg",
                    "http://localhost:3000/onePlus.jpg",
                    "http://localhost:3000/onePlus.jpg"
                ],
        "alt": "alt18",
        "description": "17Lorem ipsum dolor sit amet consectetur adipisicing elit. Facere natus cum ex rerum possimus libero ipsum soluta a aspernatur delectus qui eos, tempore sapiente incidunt sint ea maiores repellendus esse!",
        "colors": ["black",
                    "darkblue",
                    "white",
                    "green"
                ],
        "infos": ["Capacity", "RAM", "Display", "Battery"],
        "infosvalue": ["256GB", "12Go", "6.7'", "5400 mAh"],
        "reviewn1": "Sarah",
        "reviewn2": "Faizal",
        "reviewd1": "7/3/24",
        "reviewd2": "1/3/24",
        "reviewt1": "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Beatae hic impedit ipsum aperiam, ipsam expedita fuga quidem sint dolorum inventore.",
        "reviewt2": "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Beatae hic impedit ipsum aperiam, ipsam expedita fuga quidem sint dolorum inventora."
    },
    {
        "_id": 19,
        "name": "samsung galaxy s21 ultra",
        "price": 188000,
        "prix": 217000,
        "quantity": 1,
        "bigImage": ["http://localhost:3000/samsungGalaxy.jpg", 
                    "http://localhost:3000/samsungGalaxy.jpg",
                    "http://localhost:3000/samsungGalaxy.jpg",
                    "http://localhost:3000/samsungGalaxy.jpg"
                ],
        "smallImage": ["http://localhost:3000/samsungGalaxy.jpg", 
                    "http://localhost:3000/samsungGalaxy.jpg",
                    "http://localhost:3000/samsungGalaxy.jpg",
                    "http://localhost:3000/samsungGalaxy.jpg"
                ],
        "alt": "alt19",
        "description": "18Lorem ipsum dolor sit amet consectetur adipisicing elit. Facere natus cum ex rerum possimus libero ipsum soluta a aspernatur delectus qui eos, tempore sapiente incidunt sint ea maiores repellendus esse!",
        "colors": ["navy",
                    "brown",
                    "black",
                    "silver",
                ],
        "infos": ["Capacity", "RAM", "Display", "Battery"],
        "infosvalue": ["128GB", "16Go", "6.8'", "5000 mAh"],
        "reviewn1": "Sarah",
        "reviewn2": "Faizal",
        "reviewd1": "7/3/24",
        "reviewd2": "1/3/24",
        "reviewt1": "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Beatae hic impedit ipsum aperiam, ipsam expedita fuga quidem sint dolorum inventore.",
        "reviewt2": "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Beatae hic impedit ipsum aperiam, ipsam expedita fuga quidem sint dolorum inventora."
    },
    {
        "_id": 20,
        "name": "samsung curved monitor",
        "price": 200000,
        "prix": 231500,
        "quantity": 1,
        "bigImage": ["http://localhost:3000/electronic5.jpg",
                    "http://localhost:3000/electronic5.jpg",
                    "http://localhost:3000/electronic5.jpg",
                    "http://localhost:3000/electronic5.jpg"
                ],
        "smallImage": ["http://localhost:3000/electronic5.jpg",
                    "http://localhost:3000/electronic5.jpg",
                    "http://localhost:3000/electronic5.jpg",
                    "http://localhost:3000/electronic5.jpg"
                ],
        "alt": "alt20",
        "description": "19Lorem ipsum dolor sit amet consectetur adipisicing elit. Facere natus cum ex rerum possimus libero ipsum soluta a aspernatur delectus qui eos, tempore sapiente incidunt sint ea maiores repellendus esse!",
        "colors": ["black"],
        "infos": ["Brand", "Display", "Resolution", ""],
        "infosvalue": ["Samsung", "52'", "800x1200px", ""],
        "reviewn1": "Sarah",
        "reviewn2": "Faizal",
        "reviewd1": "7/3/24",
        "reviewd2": "1/3/24",
        "reviewt1": "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Beatae hic impedit ipsum aperiam, ipsam expedita fuga quidem sint dolorum inventore.",
        "reviewt2": "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Beatae hic impedit ipsum aperiam, ipsam expedita fuga quidem sint dolorum inventora."
    },
    {
        "_id": 21,
        "name": "USB Lightning",
        "price": 3000,
        "prix": 3400,
        "quantity": 1,
        "bigImage": ["http://localhost:3000/electronic4.jpg",
                    "http://localhost:3000/electronic4.jpg",
                    "http://localhost:3000/electronic4.jpg",
                    "http://localhost:3000/electronic4.jpg"
                ],
        "smallImage": ["http://localhost:3000/electronic4.jpg",
                    "http://localhost:3000/electronic4.jpg",
                    "http://localhost:3000/electronic4.jpg",
                    "http://localhost:3000/electronic4.jpg"
                ],
        "alt": "alt21",
        "description": "20Lorem ipsum dolor sit amet consectetur adipisicing elit. Facere natus cum ex rerum possimus libero ipsum soluta a aspernatur delectus qui eos, tempore sapiente incidunt sint ea maiores repellendus esse!",
        "colors": ["black", "white"],
        "infos": ["Brand", "Height", "Port", "width"],
        "infosvalue": ["Fonken", "20cm", "USB-C 3.1", "4cm"],
        "reviewn1": "Sarah",
        "reviewn2": "Faizal",
        "reviewd1": "7/3/24",
        "reviewd2": "1/3/24",
        "reviewt1": "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Beatae hic impedit ipsum aperiam, ipsam expedita fuga quidem sint dolorum inventore.",
        "reviewt2": "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Beatae hic impedit ipsum aperiam, ipsam expedita fuga quidem sint dolorum inventora."
    },
]; 

exports.find = () => {
    return new Promise((resolve, reject) => resolve(JSON.parse(JSON.stringify(products))));
}

exports.findById = (id) => {
    return new Promise((resolve, reject) =>
        resolve(JSON.parse(JSON.stringify(products)).find(product =>
            product._id == id)
        )
    );
}